"""Run the ast-grep scan engine (injected for tests) and normalize its JSON.

ast-grep is a static Rust/tree-sitter binary: ~90x faster than semgrep on a real
repo and ~165x faster to start, with no Python runtime of its own. Two of its
conventions have to be translated here, and both are easy to get silently wrong:

  • lines are 0-INDEXED (everything downstream is 1-indexed);
  • rule metadata travels in the results via `--include-metadata` (ast-grep 0.44+),
    so each rule's {kind, vendor, techKey} flows through the SAME channel as the
    match — no second read of the rule file in production. If the engine did not
    echo metadata (an older build, or an injected test fake), we fall back to
    reading the rule file back, lazily.

Rule ids are `{base}@{language}` because ast-grep rules are single-language; the
suffix is stripped so downstream code sees the base id.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import yaml


def _default_run(args: list) -> str:  # pragma: no cover - spawns the real engine
    proc = subprocess.run(args, capture_output=True, text=True, timeout=600)
    return proc.stdout


def _rule_metadata(ruleset_path: str) -> dict:
    """base rule id -> {kind, vendor, techKey}, read back from the rule file.

    FALLBACK ONLY: with `--include-metadata` the engine echoes this in the results
    (see run_scan). This path exists for an engine that doesn't, and for injected
    test fakes that emit bare matches.
    """
    try:
        with open(ruleset_path, encoding="utf-8") as fh:
            docs = list(yaml.safe_load_all(fh))
    except (OSError, yaml.YAMLError):
        return {}
    return {str(d["id"]).split("@")[0]: (d.get("metadata") or {})
            for d in docs if isinstance(d, dict) and d.get("id")}


# Directories whose contents are not production integrations. Test fixtures and
# mocks hard-code fake hosts ("production.com", "sandbox.com") and vendored code
# belongs to someone else — counting either as an integration is noise. NOTE:
# the eval's `noise` metric does NOT catch this class — score.py counts
# UNCLASSIFIED hosts, and a bundled library's Dailymotion detection is
# classified, so it passes the eval silently. The guards are the unit tests in
# `tests/test_engine_runner.py` and the corpus comparison in docs/superpowers/plans/2026-08-19-vendored-asset-noise.md.
# semgrep skipped tests by
# default; ast-grep does not, so the skip is explicit here.
#
# Filtered on the path RELATIVE to the scanned repo, not via engine globs: a glob
# would also match the absolute prefix, so scanning a fixture that itself lives
# under a `tests/` directory would silently return nothing.
_SKIP_DIRS = {"test", "tests", "spec", "__tests__", "vendor", "node_modules",
              ".venv", "dist", "build", "target", "__pycache__"}

# Third-party UI libraries checked into the tree. They ship URLs in their OWN source — CKEditor
# lists the video providers it can embed, Fancybox lists media hosts, Leaflet lists tile
# providers — so reading them as first-party code invents integrations. On a real 19-repo scan
# this produced "this inventory system calls Dailymotion" from public/js/ckeditor/ckeditor.js:5.
#
# Matched on the FILENAME, never the directory. That distinction is the whole point: skipping
# `lib`/`libs`/`plugins`/`vendors` was measured to drop 449 of 2375 call-sites including 219
# Amazon SP-API, because clients vendor Amazon's SDK into application/libraries/amazon-sp-api/.
# A vendored SDK is a genuine integration; a vendored widget is not, and only the filename can
# tell them apart.
#
# It FAILS SAFE: an unlisted library stays noisy, which is a far smaller harm than an over-broad
# entry silently suppressing a real finding. This list is the ONLY mechanism — nothing catches
# an unnamed bundle, so it WILL go stale as new libraries appear in client repos, and adding an
# entry when that happens is the accepted maintenance cost. A content-based fallback (skip any
# file with a long line, on the theory that only minified/generated code has one) was tried and
# measured against a real 19-repo scan: it destroyed 434 real call-sites, including 167 Amazon
# SP-API, 185 Amazon AWS, 41 eBay, and 41 FedEx. Generated SDK code is generated by definition —
# OpenAPI generators emit long lines — and that generated SDK code IS the integration evidence
# (e.g. application/libraries/amazon-sp-api/lib/Api/OrdersApi.php). A long-line heuristic cannot
# tell a minified widget from a generated SDK; do not re-add it.
#
# Matched on a TOKEN BOUNDARY, not a bare substring. `ckeditor`/`summernote`/`fancybox`/
# `tinymce`/`owl.carousel`/`jquery.lazy` are distinctive enough that a substring is safe, but
# `gmaps`/`leaflet`/`highchart`/`metronic` are generic enough that a bare substring also hits
# legitimate first-party files a PHP shop names after the API it wraps — GmapsController.php,
# LeafletMapWidget.php — which is the exact harm the fail-safe paragraph above warns against.
# Measured against the real 19-repo scan, the boundary rule drops the identical 99 call-sites
# the bare substring did: precision cost nothing.
_VENDORED_FILES = ("ckeditor", "summernote", "fancybox", "tinymce", "leaflet", "metronic",
                   "highchart", "gmaps", "owl.carousel", "jquery.lazy")

_VENDORED_FILE_RE = re.compile(
    r"(?<![a-z0-9])(?:" + "|".join(re.escape(lib) for lib in _VENDORED_FILES) + r")(?![a-z0-9])")


# Generated SERVICE DESCRIPTORS shipped inside an SDK. An SDK vendors a spec for every
# service its vendor sells, not the ones you use: the AWS PHP SDK carries ~200, so a repo
# calling S3 and SQS also holds machine-generated specs for CloudSearch, CloudFormation,
# Route53 and the rest — each yielding a distinct host with one "call-site" nobody makes.
# Measured at 174 attributed call-sites, and the reason "Amazon AWS" looked like the
# fleet's largest integration.
#
# Matched by FILENAME for the same reason as _VENDORED_FILES: the SDK's real client code
# sits in the same tree (Aws/S3/S3Client.php next to Aws/data/s3/…/api-2.json.php), so a
# directory rule would take both — the failure the vendored-asset spec rejected. These
# names are generated and unmistakable; nothing hand-written is called `api-2.json.php`.
_SDK_DATA_FILES = ("api-1.json", "api-2.json", "paginators-1.json", "waiters-1.json",
                   "waiters-2.json", "smoke.json", "endpoints.json", "manifest.json",
                   "aliases.json", "endpoints_prefix_history.json")


def _is_sdk_descriptor(name: str) -> bool:
    """A generated API-specification file — it DESCRIBES an API rather than calling one."""
    n = name.lower()
    # a bare stem or a language wrapper around it (`api-2.json`, `api-2.json.php`)
    return any(n == d or n.startswith(d + ".") for d in _SDK_DATA_FILES)


def _is_vendored_asset(name: str) -> bool:
    """Is this FILENAME a checked-in third-party library or a build artifact?"""
    n = name.lower()
    if ".min." in n or ".bundle." in n:
        return True
    if _is_sdk_descriptor(n):
        return True
    return bool(_VENDORED_FILE_RE.search(n))


def _is_skipped(file_path: str, repo_path: str) -> bool:
    try:
        rel = Path(file_path).resolve().relative_to(Path(repo_path).resolve())
    except ValueError:
        rel = Path(file_path)
    if any(part in _SKIP_DIRS for part in rel.parts[:-1]):
        return True
    return _is_vendored_asset(rel.name)


def run_scan(repo_path: str, ruleset_path: str, *, engine: str = "ast-grep",
             run=_default_run) -> dict:
    out = run([engine, "scan", "-r", ruleset_path, "--include-metadata",
               "--json=compact", repo_path])
    errors = []
    try:
        data = json.loads(out) if out and out.strip() else []
    except ValueError as exc:
        # A crash mid-write, or a warning line before the JSON, must NOT read as
        # "scanned cleanly, found nothing" — that is indistinguishable from a clean
        # repo all the way through to a KNOWN verdict. Fail loud.
        data = []
        errors.append({"message": f"engine output was not valid JSON ({exc}); "
                                  "treating the scan as FAILED, not empty",
                       "path": repo_path})
    meta_by_rule = None                      # lazy: only re-read the rule file if the
    matches = []                             # engine did not echo metadata for a match
    for m in data:
        if _is_skipped(m.get("file", ""), repo_path):
            continue
        base = str(m.get("ruleId", "")).split("@")[0]
        meta = m.get("metadata")
        if meta is None:                     # engine didn't echo it (old build / test fake)
            if meta_by_rule is None:
                meta_by_rule = _rule_metadata(ruleset_path)
            meta = meta_by_rule.get(base, {})
        matches.append({
            "checkId": base,
            "vendor": meta.get("vendor", ""), "techKey": meta.get("techKey", ""),
            "kind": meta.get("kind", ""),
            "path": m.get("file", ""),
            "line": ((m.get("range") or {}).get("start") or {}).get("line", -1) + 1,
            # the FULL matched text: a multi-line string literal carries content past
            # its start line (an XML request root often sits on line 2 of the literal)
            "text": m.get("text", "") or "",
        })
    return {"matches": matches, "scanned": [], "errors": errors}
